allow parameter to md2deck call

diff --git a/md2deck/loop b/md2deck/loop
--- a/md2deck/loop
+++ b/md2deck/loop
@@ -2,13 +2,22 @@
 set -e -E -u
 
 PORT=8080
+ONCE=false
 
-live-server --port=$PORT /target &
+PARAM=${1:-loop}
+case $PARAM in
+    shell)  bash -i && exit;;
+    --once) ONCE=true;;
+    loop)   ;;
+    *)      echo "unknown parameter '$PARAM' given, aborting here..." && exit 1;;
+esac
+
+
+$ONCE || live-server --port=$PORT /target &
 
 ln -sf /target/rendered .
 while true; do
     [[ -d /target/rendered ]] || mkdir -p /target/rendered
-    echo -e "\n\n\n\n\n\n\n\n\n\n"
 
     echo "-------- rsync output --------"
     rsync -Pav /source/assets /md2deck/assets /target/ || :
@@ -41,10 +50,12 @@ while true; do
         /source/slides.md || :
     echo "-------- /pandoc output --------"
     echo
+    $ONCE && break
 
     sleep .5
     echo -e "\n\n\nopen http://localhost:$PORT\n\n(... or use Ctrl-C to stop md2deck)\n\n\n"
     inotifywait -r -q /source/
+    echo -e "\n\n\n\n\n\n\n\n\n\n"
 done
 
 echo "done."
